[build]
  # Build command
  command = "yarn build"
  
  # Directory to publish
  publish = "dist"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS = "--version"
    NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  # Skip processing of certain files
  skip_processing = false

[build.processing.css]
  # Minify CSS
  bundle = true
  minify = true

[build.processing.js]
  # Minify JavaScript
  bundle = true
  minify = true

[build.processing.html]
  # Minify HTML
  pretty_urls = true

# Redirects for SPA routing
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Note: SSR function removed for simplicity
# Using client-side rendering with SPA routing
